[build]
  base = "."                       # Base directory of your project
  publish = "static"               # Directory for static files (your frontend)
  command = "pip install -r requirements.txt" # Install backend dependencies

[functions]
  directory = "netlify/functions"  # Directory where Netlify functions (your backend) are located
  python_runtime = "python3.8"     # Specify Python version

[dev]
  command = "flask run"            # Command for local development (if needed)